<a href="https://colab.research.google.com/github/Varshitha019/Python_Programming_in_DA_and_ML/blob/master/Day3_Session2_Pandas_and_Numpy_Exercise_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])



In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64



#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type



In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]


In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64



#Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)



Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


#Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000



In [ ]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


#Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.


In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'14FRF3bBS_lVP5FZDBV8HQalrOB_sLP6Z'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
                                                cast  ...   id
0  [{'cast_id': 14, 'character': 'Woody (voice)',...  ...  862

[1 rows x 3 columns]


#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields 


In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)


Details of the seventh movie:
cast    [{'cast_id': 1, 'character': "Savannah 'Vannah...
crew    [{'credit_id': '52fe44779251416c91011acb', 'de...
id                                                  31357
Name: 3, dtype: object


#Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields


In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

#Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv


In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
# Create a smaller dataframe
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime']]
result = small_df.sort_values('release_date')
print("DataFrame based on country and language.")
print(result)

#15.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable


In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.55403902 0.48386688 0.30929187 0.57812114]
 [0.51341506 0.15117433 0.1782613  0.79276791]
 [0.33480764 0.58999023 0.97208314 0.03667922]
 [0.20145195 0.45313571 0.19210394 0.53570716]]


#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.


In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.02185204 0.65707828 0.42157513 0.20979514 0.68763125 0.83388599
  0.30966935 0.79945581 0.09942068 0.08374875]
 [0.34196631 0.84320539 0.43484943 0.44669551 0.66879818 0.22363841
  0.77502849 0.99212069 0.73642829 0.97336229]
 [0.06193986 0.57266468 0.30723945 0.53096654 0.74066931 0.51656498
  0.50050256 0.10088953 0.2539383  0.73539719]
 [0.46608638 0.91944886 0.89328454 0.26624183 0.39461186 0.38950808
  0.47048132 0.87036717 0.49327395 0.90400365]
 [0.19135083 0.78849445 0.45529815 0.43963166 0.43219718 0.11380324
  0.9011056  0.78891722 0.21908082 0.01000153]
 [0.18437533 0.30100168 0.30708617 0.56711725 0.82236452 0.7272448
  0.24752911 0.23747516 0.15540792 0.52069761]
 [0.84649002 0.89110037 0.03266249 0.48916129 0.43953048 0.80230083
  0.5081123  0.62561411 0.39729081 0.23072154]
 [0.8059715  0.74728907 0.38749681 0.9102042  0.18368067 0.27127033
  0.19287988 0.64990723 0.25725774 0.09076546]
 [0.02515341 0.46455605 0.0179992  0.09164282 0.28534055 0.438107

#Write a NumPy program to generate 8 random integers between 100 and 300


In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[176 212 288 194 204 188 193 185]


#Write a NumPy program to create a random integer nos of size 20 and sort it


In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.32488516 0.41105713 0.03053437 0.4031598  0.12336099 0.63010763
 0.29700357 0.23504826 0.38270483 0.95783803 0.92800405 0.47175585
 0.29139521 0.80740077 0.03783516 0.86570991 0.3292657  0.26545856
 0.51609303 0.07011576]
Sorted array:
[0.03053437 0.03783516 0.07011576 0.12336099 0.23504826 0.26545856
 0.29139521 0.29700357 0.32488516 0.3292657  0.38270483 0.4031598
 0.41105713 0.47175585 0.51609303 0.63010763 0.80740077 0.86570991
 0.92800405 0.95783803]
