<a href="https://colab.research.google.com/github/Varshitha019/Python_Programming_in_DA_and_ML/blob/master/Day3_Session2_Pandas_Worked_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
pip install pandas


#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10



In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


#Write a Pandas program to convert a Panda module Series to Python list and its type.




In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)	
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
	



In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


##Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]




In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


##Write a Pandas program to convert a dictionary to a Pandas series.
Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}


In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50]


In [17]:
pip install numpy

In [ ]:

import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
['100', '200', 'python', '300.12', '400']
	


In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.


In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to sort a given Series.


In [ ]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)	
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.



In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.



In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.


In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.



In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [18]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [22]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [24]:
downloaded = drive.CreateFile({'id':'14FRF3bBS_lVP5FZDBV8HQalrOB_sLP6Z'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).
	


In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'14FRF3bBS_lVP5FZDBV8HQalrOB_sLP6Z'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 


import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)


First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
Columns of the DataFrame:
Index(['cast', 'crew', 'id'], dtype='object')


#Write a Pandas program to sort the DataFrame based on country from dataset of 



In [ ]:

import pandas as pd
import numpy as np
df = pd.read_csv('movie_metadata.csv')
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)



#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)


Columns of the DataFrame:
Index(['cast', 'crew', 'id'], dtype='object')


#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [28]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)


Details of the third moviee:
cast    [{'cast_id': 2, 'character': 'Max Goldman', 'c...
crew    [{'credit_id': '52fe466a9251416c75077a89', 'de...
id                                                  15602
Name: 2, dtype: object


#Write a Pandas program to display the first 10 rows of the DataFrame.


In [29]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)


First 10 rows of the DataFrame:
                                                cast  ...     id
0  [{'cast_id': 14, 'character': 'Woody (voice)',...  ...    862
1  [{'cast_id': 1, 'character': 'Alan Parrish', '...  ...   8844
2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...  ...  15602
3  [{'cast_id': 1, 'character': "Savannah 'Vannah...  ...  31357
4  [{'cast_id': 1, 'character': 'George Banks', '...  ...  11862
5  [{'cast_id': 25, 'character': 'Lt. Vincent Han...  ...    949
6  [{'cast_id': 1, 'character': 'Linus Larrabee',...  ...  11860
7  [{'cast_id': 2, 'character': 'Tom Sawyer', 'cr...  ...  45325
8  [{'cast_id': 1, 'character': 'Darren Francis T...  ...   9091
9  [{'cast_id': 1, 'character': 'James Bond', 'cr...  ...    710

[10 rows x 3 columns]


#Write a Pandas program to get the elements of an array values into column-wise.

In [25]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

                                                cast  ...   id
0  [{'cast_id': 14, 'character': 'Woody (voice)',...  ...  862

[1 rows x 3 columns]


#**NUMPY EXAMPLES**


#Write a NumPy program to generate five random numbers from the normal distribution.

In [30]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[0.87822821 1.13348961 0.93830722 0.51845009 0.75886866]


#Write a NumPy program to generate six random integers between 10 and 30


In [31]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[28 10 27 19 28 28]


#Write a NumPy program to create a 3x3x3 array with random values.

In [32]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.94087614 0.88260574 0.69068312]
  [0.18172071 0.77647364 0.13985962]
  [0.95093578 0.52154821 0.99147094]]

 [[0.81142557 0.61291085 0.36360594]
  [0.87933158 0.1779084  0.43967388]
  [0.80745073 0.90373702 0.1219361 ]]

 [[0.82333014 0.45109131 0.42349575]
  [0.18618478 0.59206198 0.43182818]
  [0.56972591 0.39532863 0.81543572]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.


In [33]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.25722418 0.44590799 0.48650195 0.41095545 0.02494238]
 [0.92819568 0.99988297 0.21446892 0.24397353 0.48825407]
 [0.35757695 0.52917872 0.13455785 0.28424818 0.14422093]
 [0.32381947 0.74844393 0.7053557  0.47088591 0.10451988]
 [0.60209418 0.17866121 0.56498516 0.60118722 0.40587924]]
Minimum and Maximum Values:
0.02494237622199169 0.9998829699861906


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [34]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.62522718 0.05085793 0.20443354 0.87762297]
 [0.11618714 0.89892859 0.34112166 0.90317657]
 [0.68800373 0.89502394 0.44574831 0.66891963]
 [0.90213968 0.74266106 0.55160705 0.98735654]
 [0.95915893 0.69103483 0.60432905 0.05980914]
 [0.94881086 0.1756187  0.68503361 0.82499892]
 [0.25004633 0.44426008 0.51831563 0.61489524]
 [0.2976297  0.17981403 0.33290679 0.56353421]
 [0.18341163 0.64710958 0.89609387 0.72065771]
 [0.4762987  0.0738786  0.1337462  0.59907922]]
First 5 rows of the above array:
[[0.62522718 0.05085793 0.20443354 0.87762297]
 [0.11618714 0.89892859 0.34112166 0.90317657]
 [0.68800373 0.89502394 0.44574831 0.66891963]
 [0.90213968 0.74266106 0.55160705 0.98735654]
 [0.95915893 0.69103483 0.60432905 0.05980914]]
First 3 columns of the above array:
[[0.62522718 0.05085793 0.20443354 0.87762297]
 [0.11618714 0.89892859 0.34112166 0.90317657]
 [0.68800373 0.89502394 0.44574831 0.66891963]
 [0.90213968 0.74266106 0.55160705 0.98735654]
 [0.95915893 0.6910

#Write a NumPy program to shuffle numbers and find permutation between 0 and 10 (inclusive).

In [35]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[0 7 8 2 6 3 9 1 5 4]
Same result using permutation():
[4 9 8 1 3 2 6 0 7 5]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [36]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.12876678 0.64987342 0.73988318 0.03611556 0.04607029 0.6351437
 0.06976653 0.31157878 0.85546789 0.7034877 ]
Sorted array:
[0.03611556 0.04607029 0.06976653 0.12876678 0.31157878 0.6351437
 0.64987342 0.7034877  0.73988318 0.85546789]


#Write a NumPy program to create a random integer nos of size 10 and sort it.


In [37]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[8 3 7 9 6 0 2 5 4 1]
[0 1 2 3 4 5 6 7 8 9]
